# Generated by Django 5.2.13 on 2026-04-11 13:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('raw_data', models.TextField()),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain'), ('url', 'URL'), ('hash', 'Hash'), ('cve', 'CVE'), ('email', 'Email')], max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('threat_score', models.IntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Malware',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('hash_value', models.CharField(max_length=255, unique=True)),
                ('hash_type', models.CharField(default='sha256', max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatActor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('aliases', models.JSONField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('uses', 'USES'), ('targets', 'TARGETS'), ('related', 'RELATED_TO'), ('drops', 'DROPS'), ('communicates', 'COMMUNICATES_WITH')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_ioc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_rel', to='threatintel.ioc')),
                ('target_ioc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_rel', to='threatintel.ioc')),
            ],
        ),
    ]
