# Generated by Django 5.2.13 on 2026-04-24 16:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threatintel', '0002_ioc_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ioc',
            name='type',
            field=models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain'), ('url', 'URL'), ('hash', 'Hash'), ('md5', 'MD5'), ('sha1', 'SHA1'), ('sha256', 'SHA256'), ('cve', 'CVE'), ('email', 'Email')], max_length=20),
        ),
    ]
