# Generated by Django 5.2.13 on 2026-04-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threatintel', '0004_alter_event_timestamp'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ioc',
            name='unique_ioc_value_type_source',
        ),
        migrations.AddField(
            model_name='ioc',
            name='times_seen',
            field=models.IntegerField(default=1),
        ),
    ]
