# Generated by Django 5.2.13 on 2026-04-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threatintel', '0005_remove_ioc_unique_ioc_value_type_source_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ioc',
            constraint=models.UniqueConstraint(fields=('value', 'type'), name='unique_ioc_value_type'),
        ),
    ]
